"""
Automatic payment-reminder engine for unpaid / partial GST invoices.

Runs once a day (default 09:00 IST) as an APScheduler background job
started from `server.py` startup. For every invoice that is NOT fully paid,
we look at `age_in_days = (today - invoice_created_at).days` and fire a
WhatsApp reminder on days {1, 3, 7, 14, 21, 28, 35, …} (i.e. day 1, day 3,
day 7, then weekly).

A record of every attempt is pushed into `invoices.reminders_sent[]` so
we never re-fire the same reminder day twice — even across service restarts.

The message includes: customer name, due amount, invoice #, and a UPI
intent link generated by `routes.gst_invoices.build_upi_link()` so the
user can pay in one tap from WhatsApp.

Endpoints exposed (under /api/gst/reminders):
  POST /run-now      — manually trigger the scan (admin only; useful for testing)
  GET  /status       — scheduler status + last-run info
  POST /invoices/{id}/send  — fire a one-off reminder for a single invoice
"""
from __future__ import annotations

import asyncio
import logging
import os
from datetime import datetime, timezone, timedelta
from typing import Dict, List, Optional

from apscheduler.schedulers.asyncio import AsyncIOScheduler
from apscheduler.triggers.cron import CronTrigger
from fastapi import APIRouter, HTTPException

from db_client import get_db

router = APIRouter(prefix="/gst/reminders", tags=["GST Reminders"])
logger = logging.getLogger(__name__)
db = get_db()

# ---- Reminder day schedule ----
# Day 1, 3, 7, then every 7 days thereafter (max 60 days).
# Change via env: REMINDER_SCHEDULE="1,3,7,14,21,28" (comma-sep).
_default_schedule = "1,3,7,14,21,28,35,42,49,56"
REMINDER_DAYS = sorted({int(x) for x in os.environ.get("REMINDER_SCHEDULE", _default_schedule).split(",") if x.strip().isdigit()})

REMINDER_CRON_HOUR = int(os.environ.get("REMINDER_CRON_HOUR", "9"))
REMINDER_CRON_MINUTE = int(os.environ.get("REMINDER_CRON_MINUTE", "0"))
REMINDER_TIMEZONE = os.environ.get("REMINDER_TIMEZONE", "Asia/Kolkata")

# Global scheduler handle so status/run-now can inspect it
_scheduler: Optional[AsyncIOScheduler] = None
_last_run: Dict = {"started_at": None, "finished_at": None, "processed": 0, "sent": 0, "errors": 0}


def _days_since(iso: str) -> int:
    try:
        dt = datetime.fromisoformat(iso.replace("Z", "+00:00"))
        return max(0, (datetime.now(timezone.utc) - dt).days)
    except Exception:
        return 0


def _due_reminder_day(age_days: int, already_sent_days: List[int]) -> Optional[int]:
    """Pick the schedule day we should fire today (if any).

    Logic:
      • If today matches an exact schedule day and that day hasn't been sent, fire it.
      • Otherwise, if the invoice aged past a schedule day that was missed
        (e.g. service was down on day 3), catch up and fire the most recent
        missed one.
    """
    due_days = [d for d in REMINDER_DAYS if d <= age_days and d not in already_sent_days]
    if not due_days:
        return None
    return max(due_days)  # Fire the most recent missed day only (avoid spamming)


async def _send_whatsapp_reminder(invoice: dict, day: int) -> Dict:
    """Send a WhatsApp reminder for one invoice. Tries to attach a UPI QR code
    as a document first; always includes the UPI intent link in the caption.
    Respects opt-outs — any customer who sent STOP will be silently skipped."""
    # Lazy import to avoid a circular with gst_invoices at module load
    from routes.gst_invoices import build_upi_link, get_upi_for_invoice, render_qr_png_bytes
    from routes.whatsapp import get_whatsapp_settings, _is_opted_out

    cust = invoice.get("customer") or {}
    phone = (cust.get("phone") or "").replace(" ", "").replace("+", "").replace("-", "")
    if len(phone) == 10:
        phone = "91" + phone
    if not phone:
        return {"success": False, "error": "no customer phone"}

    due_amount = float(invoice.get("due_amount") or 0)
    if due_amount <= 0:
        return {"success": False, "error": "no due amount"}

    # Respect STOP / opt-out — never message customers who've unsubscribed.
    try:
        if await _is_opted_out(phone):
            return {"success": False, "error": "opted_out", "opted_out": True}
    except Exception:
        pass  # Never let opt-out lookup break a reminder run

    upi = get_upi_for_invoice(invoice)
    upi_link = build_upi_link(invoice, due_amount)
    text = (
        f"Dear {cust.get('name', 'Customer')[:40]},\n\n"
        f"Your solar payment of ₹ {due_amount:,.2f} is pending on invoice "
        f"{invoice.get('invoice_number')}.\n\n"
        f"Pay now — one tap:\n{upi_link}\n\n"
        f"Or use {upi['bank']} UPI: {upi['vpa']}\n\n"
        f"ASR Enterprises\nCall/WhatsApp: 9296389097\n\n"
        f"Reply STOP to unsubscribe."
    )

    try:
        settings = await get_whatsapp_settings()
        token = (settings or {}).get("access_token", "").strip()
        phone_id = (settings or {}).get("phone_number_id", "").strip()
        if not token or not phone_id:
            return {"success": False, "error": "whatsapp not configured"}

        import httpx

        async with httpx.AsyncClient(timeout=30.0) as client:
            # 1) Try to upload & send the QR PNG as a WhatsApp image message
            try:
                qr_png = render_qr_png_bytes(upi_link, box=10, border=3)
                up = await client.post(
                    f"https://graph.facebook.com/v20.0/{phone_id}/media",
                    headers={"Authorization": f"Bearer {token}"},
                    files={"file": (f"{invoice.get('invoice_number','inv').replace('/', '_')}.png", qr_png, "image/png")},
                    data={"messaging_product": "whatsapp", "type": "image/png"},
                )
                if up.status_code in (200, 201):
                    media_id = up.json().get("id", "")
                    if media_id:
                        send = await client.post(
                            f"https://graph.facebook.com/v20.0/{phone_id}/messages",
                            headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
                            json={
                                "messaging_product": "whatsapp",
                                "to": phone,
                                "type": "image",
                                "image": {"id": media_id, "caption": text},
                            },
                        )
                        if send.status_code in (200, 201):
                            return {"success": True, "channel": "image+caption", "day": day}
            except Exception as qr_err:
                logger.warning(f"[reminder] QR image send failed for {invoice.get('invoice_number')}: {qr_err}")

            # 2) Fallback: plain text message
            resp = await client.post(
                f"https://graph.facebook.com/v20.0/{phone_id}/messages",
                headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
                json={"messaging_product": "whatsapp", "to": phone, "type": "text", "text": {"body": text}},
            )
            if resp.status_code in (200, 201):
                return {"success": True, "channel": "text", "day": day}
            return {"success": False, "error": f"{resp.status_code}: {resp.text[:200]}"}
    except Exception as e:
        logger.warning(f"[reminder] send failed for {invoice.get('invoice_number')}: {e}")
        return {"success": False, "error": str(e)}


async def scan_and_send_reminders() -> Dict:
    """Scan all unpaid/partial invoices and fire whichever reminder is due today."""
    global _last_run
    _last_run = {
        "started_at": datetime.now(timezone.utc).isoformat(),
        "finished_at": None, "processed": 0, "sent": 0, "errors": 0,
    }

    cursor = db.invoices.find(
        {
            "doc_type": "invoice",
            "payment_status": {"$in": ["unpaid", "partial"]},
            "due_amount": {"$gt": 0},
        },
        {"_id": 0},
    )
    async for inv in cursor:
        _last_run["processed"] += 1
        try:
            age = _days_since(inv.get("created_at") or "")
            if age < (REMINDER_DAYS[0] if REMINDER_DAYS else 1):
                continue
            sent_days = [int(r.get("day") or 0) for r in (inv.get("reminders_sent") or [])]
            day = _due_reminder_day(age, sent_days)
            if day is None:
                continue

            # Refetch invoice to catch any concurrent payment
            live = await db.invoices.find_one({"id": inv["id"]}, {"_id": 0})
            if not live or live.get("payment_status") == "paid":
                continue

            result = await _send_whatsapp_reminder(live, day)
            entry = {
                "day": day,
                "sent_at": datetime.now(timezone.utc).isoformat(),
                "result": "sent" if result.get("success") else "failed",
                "channel": result.get("channel", ""),
                "error": result.get("error", ""),
                "due_amount_at_send": float(live.get("due_amount") or 0),
            }
            await db.invoices.update_one(
                {"id": live["id"]},
                {"$push": {"reminders_sent": entry}},
            )
            if result.get("success"):
                _last_run["sent"] += 1
            else:
                _last_run["errors"] += 1
        except Exception as e:
            _last_run["errors"] += 1
            logger.exception(f"[reminder] unexpected error processing {inv.get('invoice_number')}: {e}")

    _last_run["finished_at"] = datetime.now(timezone.utc).isoformat()
    logger.info(f"[reminder] scan done — processed={_last_run['processed']} sent={_last_run['sent']} errors={_last_run['errors']}")
    return _last_run


def start_reminder_scheduler() -> None:
    """Called once from `server.py` application startup to launch the daily cron."""
    global _scheduler
    if _scheduler is not None and _scheduler.running:
        return
    _scheduler = AsyncIOScheduler(timezone=REMINDER_TIMEZONE)
    _scheduler.add_job(
        scan_and_send_reminders,
        trigger=CronTrigger(hour=REMINDER_CRON_HOUR, minute=REMINDER_CRON_MINUTE),
        id="gst_payment_reminders",
        replace_existing=True,
        misfire_grace_time=3600,
    )
    _scheduler.start()
    logger.info(
        f"[reminder] scheduler started — daily @ {REMINDER_CRON_HOUR:02d}:{REMINDER_CRON_MINUTE:02d} "
        f"{REMINDER_TIMEZONE}; schedule_days={REMINDER_DAYS}"
    )


# ==================== API ENDPOINTS ====================
@router.post("/run-now")
async def run_now():
    """Manually kick the reminder scan (useful for testing/admin UI button)."""
    result = await scan_and_send_reminders()
    return {"success": True, "result": result}


@router.get("/status")
async def scheduler_status():
    running = bool(_scheduler and _scheduler.running)
    next_run = None
    if running:
        job = _scheduler.get_job("gst_payment_reminders")
        if job and job.next_run_time:
            next_run = job.next_run_time.isoformat()
    return {
        "running": running,
        "schedule_days": REMINDER_DAYS,
        "cron": f"{REMINDER_CRON_HOUR:02d}:{REMINDER_CRON_MINUTE:02d} {REMINDER_TIMEZONE}",
        "next_run": next_run,
        "last_run": _last_run,
    }


@router.post("/invoices/{invoice_id}/send")
async def send_one(invoice_id: str):
    """Fire a single reminder now, regardless of schedule. Useful for the admin
    'Send Reminder' button in the invoice list."""
    inv = await db.invoices.find_one({"id": invoice_id}, {"_id": 0})
    if not inv:
        raise HTTPException(404, "Invoice not found")
    if inv.get("payment_status") == "paid":
        raise HTTPException(400, "Invoice is already paid.")
    if inv.get("doc_type") != "invoice":
        raise HTTPException(400, "Reminders are only for invoices, not quotations.")

    age = _days_since(inv.get("created_at") or "")
    day_label = max(1, age)  # For the log — "manual/day N"
    result = await _send_whatsapp_reminder(inv, day_label)
    entry = {
        "day": day_label,
        "sent_at": datetime.now(timezone.utc).isoformat(),
        "result": "sent" if result.get("success") else "failed",
        "channel": result.get("channel", ""),
        "error": result.get("error", ""),
        "manual": True,
        "due_amount_at_send": float(inv.get("due_amount") or 0),
    }
    await db.invoices.update_one({"id": invoice_id}, {"$push": {"reminders_sent": entry}})
    return {"success": result.get("success", False), "result": result, "entry": entry}
